# Generated by Django 3.0.7 on 2021-01-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaksh', '0035_auto_20201224_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='negative_weightage',
            field=models.FloatField(default=0, help_text='Will be considered as Negative percentage per question'),
        ),
    ]
